name: update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - run: |
          go generate ./...

      - name: commit and create a pull request
        uses: shogo82148/actions-commit-and-create-pr@v1
